### PR TITLE
Http host and port provisioning with X-Forwarded headers

### PR DESCRIPTION
**Pull request by mmatczuk**
A server modification that allows http tunneling to any port using X-Forwarded-Port http header. X-Forwarded-Host is also supported for host overwriting.

### CODE REVIEW

**Comment by mmatczuk** [comment]
1.5 race check failure is not related to the submitted code, what should I do?

**Comment by cihangir** [comment]
cc @rjeczalik

**Comment by rjeczalik** [comment]
@mmatczuk The races are going to be fixed with #19. You caught us having red master, not good.

Regarding this feature, could we have what Go stdlib is doing instead for [httputil.ReverseProxy](https://golang.org/pkg/net/http/httputil/#ReverseProxy), that is to add Director field:

```go
// ServerConfig ...
type ServerConfig struct {
    ...

    // Director ...
    Director func(*http.Request)

    ...
}
```

And then call it [here](https://github.com/koding/tunnel/blob/0a0e462/server.go#L137), if non-nil.

Then you can pass your custom Director function that overwrites `r.Host` with `X-Forwarded-Host:X-Forwarded-Port`. I think this would be more flexible than hardcoding this logic.

What do you think?

**Comment by mmatczuk** [comment]
This would make code more flexible indeed. I'll update PR soon.

**Comment by mmatczuk** [comment]
I removed X-Forwarded logic from this commit to keep tunnel simple. It's now available as a director [here](https://github.com/mmatczuk/tunnel-ext).

**Comment by rjeczalik** [comment]
@mmatczuk :+1:

**Pull request merged**
